from caesar_cw import encrypt, decrypt

KEY1:int = 10
KEY2:int = 500
KEY3:int = 42_069
KEY4:int = 101_702
KEY5:int = 42_921

test_words_1 = [
    "KIM CHAEWON", "MIYAWAKI SAKURA", 
    "HUH YUNJIN", "HONG EUNCHAE", 
    "KIM GARAM", "NAKAMURA KAZUHA", 
]

test_words_2 = [
    "JANG WONYOUNG", "NAOI REI", 
    "AN YUJIN", "KIM JIWON", 
    "LEE HYUNSEO", "KIM GAEUL", 
]

test_words_3 = [
    "RUKTXYLVMHZQFWBPDONSJKIECAYHGTXUQRGYKDVFUWBXJSVNAQIVYOPWCQSZXEBNORPAKJWGZMQLDTCIHYJXBFOENRAGMDLQSOWXGSKPZTYBICUVFEDJHKLXNMYRQOCJVBXSLOITGKEUMFYHWZJDNXPQVOKTJIRFZUBCWAESMQZDNYXLKUCVTISJMPFHKRQVGBIPCLJSMOZXAYHWDENQUKVLPMSAFZDTRJXFLIYVEGQOXNKCAHUIBPLJEYRQWMKZGDNXTYKIQWAOZVKFPXQYRMJCDWVZOFHLBXSKJYNQRXUDVHFCGWEIZUKDXPLSHBJQGNMOCRAFNSIYBUETRZGVDXLSMKWQJYNLHBKPOTFYUJRSOVCXWPJNMFUGXAVHYTJELBNXZWIKDQVTGOXJCBFQWYXUIZABEJSGYPKFVUNQWCDRLEXYBTHOPGAVZUQJFYNXPSTCVDOKRMWTXGYJCOEZSQNKFVLBZWYHCMKESFPWYOHJVLBHNFXQJIMWUXYZARWTGLDCQHVZJESUPBAXQJOVLMWUKANJYIHUZSXCYEBFVNMLRGXZJTYOIBHDLKNGMAJRWIEFCLNBUJVKODZWFTLAEJBYUHXSJDOWABFZKPQSGYLUNRAJQBFWOZMKXCPLTIJUBNVKGWYMLXJOVECLPTZRSQFNVGBYZOHIMUDWKYGFZIJTALQUBVCYEPHSZONXUIYACSWEDRZVFMKOGTUNWIXLAKFBDXHTJPMCSLZOQDVJPZMLYGREKFCPOJYRAQNFMLZWKUPCYIXQVRAOFDWXKBNUSJZPHCVNKYWBIRALPMGNOIVRFZCUEKPHMSVNLQBJZWMOASNHETRGXVKFDLZCOENAKQYFJPXBTLIUKDPWOBCJGZDYXEWQNHGSVQZMPKADTUIYJFXZEGPQOABRYHMLTSXNCZDEBKXHIFUVTJOQWSMLYERGVTBWUAYGZDRPHOTKQJXZFWUHLAVKEXOYJFNKUVWZAYINCDHXJMPKAVRIYQTGLNZSBKCYMQXVLTNSFZEABOQKHJSFDPRXILABJMTWUYONQZFGJLVESQKTIUPZOWYLFTXUMJBHCQFYNAVGPRDZCWQFHXLYJUWNEIQRCPJSOYDUBNKGSMZOHYIUVWXYBCDNOHAKWXVZGCMIQDLEJHZNFYCQIKXJVPMGLYIQNBUJWADFSZLGXCOBVHPKYQDXTIJFSQUMLRGEZANBUJMRLOVXGTDCINAJWOHXUSGPEFVJYHLMNTQSGZBYJAWQXPLVZGCIHESUYDOATVFNGBUELMYVPSZKNXFPZBHTIRKJAFQOCUBVTXHJYWOIQNPKVSBHPLXETUKSFIACBJZXRLQTUWOGMLKPQRBZYNCDQXSWKFZUEJITXVBAOYQJCMWVTIHJBYLFGMDKRWYUVSQKPHZXIEOSZMLGTRUHCAEFXBYVZWKLOINRYDJPVHMGUZQJXPBRGTMEKSBLDXYPHMQWGLNJROUCAJITRQYZFWANJDKSLGZYTMHNBFAIMXVQWEYCGDHOJVSMXAFZQVLYJDWNXUKPTQSGYXJMRWZGBNDAFHICVSOTQZWADYKLZOGTQRGVMFNXBHYDZUSFCPLHQMXZVBJIYFKJLRWOMNAGQDKFTUZQJWBFYRKUJQNLWZTCGELVAPFNJVZSKPDXRFYLZCXTFHKVZQWRPBCJIFUGLSYQEXSKNZHVTDOXBGURKWOMYXJABHGCPQDSRJFVNUWQRZOALMKFHDXYPZLGWOVZSUGZYPMTUKXWCJQZRGNOBICRZXVLBWKDZHYMSTQXGPEJAHNYKLBTZWIJQCXOPMLYRAOTQDFKUSXZEBNOLGDCQHXJMIAYHVFQGOTXKPQZSMNVFJYZTQXNSHFYMVXCRPNLJVZTFUHNBSMNLGZ"
]

test_words_4 = [
    "HAEWON", "LILY", 
    "JIWOO", "KYUJIN", 
    "BAE",
]

test_words_5 = [
    "NAKO", "HITOMI",
    "SAKURA", "WONYOUNG",
    "YENA", "MINJU",
    "YUJIN", "EUNBI",
    "CHAEYEON", "YURI",
    "CHAEWON", "HYEWON",
]

def test_encrypt_decrypt():
    for word in test_words_2:
        result_enc2 = encrypt(word, KEY2)
        result_dec2 = decrypt(result_enc2, KEY2)
        assert word == result_dec2
    

def main():
    test_encrypt_decrypt()


if __name__ == "__main__":
    main()